"""Lay out the film's timeline from the storyboard and the chosen narration takes.

Each beat gets a slot = narration length + GAP + its hold; a scene is LEAD_IN + its slots + TAIL,
rounded up to whole frames so scene videos concatenate to exact absolute times. Beats not yet
narrated use the storyboard's words-per-minute estimate, so scenes can be built before the voice
exists and simply stretch to fit once it does.

Writes web/timing.js (window.TIMING, for the player) and build/timing.json (for assemble.py).
"""

import json
import math
from pathlib import Path

HERE = Path(__file__).resolve().parent
FPS = 30
LEAD_IN, GAP, TAIL = 1.5, 1.0, 2.2


def build():
    sb = json.loads((HERE / "storyboard.json").read_text())
    narr_path = HERE / "build" / "narration.json"
    narration = json.loads(narr_path.read_text()) if narr_path.exists() else {}
    wpm = sb["meta"].get("words_per_minute", 140)
    scenes, start = [], 0.0
    for scene in sb["scenes"]:
        t, beats = LEAD_IN, []
        for beat in scene["beats"]:
            text = " ".join(beat.get("narration", "").split())
            if beat["id"] in narration:
                dur, wav, measured = narration[beat["id"]]["duration"], narration[beat["id"]]["wav"], True
            else:
                dur, wav, measured = (len(text.split()) / wpm * 60 if text else 0.0), None, False
            slot = dur + (GAP if text else 0) + float(beat.get("hold_seconds") or 0)
            beats.append({"id": beat["id"], "start": round(t, 3), "dur": round(dur, 3), "slot": round(slot, 3),
                          "end": round(t + slot, 3), "text": text, "onscreen_text": beat.get("onscreen_text", []),
                          "wav": wav, "measured": measured})
            t += slot
        duration = math.ceil((t + TAIL) * FPS) / FPS
        scenes.append({"id": scene["id"], "title": scene.get("title", ""), "start": round(start, 3),
                       "duration": duration, "frames": round(duration * FPS), "beats": beats})
        start += duration
    timing = {"fps": FPS, "total": round(start, 3), "scenes": scenes}
    (HERE / "build").mkdir(exist_ok=True)
    (HERE / "build" / "timing.json").write_text(json.dumps(timing, indent=1))
    (HERE / "web" / "timing.js").write_text(
        "// Generated by timing.py; do not edit.\nwindow.TIMING = " + json.dumps(timing) + ";\n")
    return timing


if __name__ == "__main__":
    t = build()
    measured = sum(b["measured"] for s in t["scenes"] for b in s["beats"])
    total_beats = sum(len(s["beats"]) for s in t["scenes"])
    print(f"{len(t['scenes'])} scenes, {total_beats} beats ({measured} with real narration), "
          f"total {int(t['total'] // 60)}:{t['total'] % 60:04.1f}")
    for s in t["scenes"]:
        print(f"  {s['id']}  {s['duration']:6.1f}s  {s['title']}")
