#!/usr/bin/env node
// Regenerate KIT.md from public factory declarations and the comments immediately above them.
import { readFile, writeFile } from 'node:fs/promises';
import path from 'node:path';

const root = process.cwd();
const sources = ['characters', 'ui', 'objects', 'docs'];
const output = ['# Kit component catalog', '', 'Generated by `node tools/kit-catalog.mjs` from `web/kit/*.js`. Components create all nodes in their factory and return `{g, update(params)}`. Position their `g` with `Engine.place`; pass scene time `t` to animated updates. `Kit.C`, `Kit.ease`, `Kit.text`, `Kit.measure`, `Kit.presence`, `Kit.show`, `Kit.group`, and `Kit.shadow` are shared helpers.', ''];
const skip = new Set(['iso', 'stripX']);
for (const file of sources) {
  const source = await readFile(path.join(root, 'web/kit', `${file}.js`), 'utf8');
  output.push(`## ${file}.js`, '');
  const exports = new Map();
  const assigned = source.match(/Object\.assign\(window\.Kit,\s*\{([\s\S]*?)\}\);/);
  if (assigned) for (const piece of assigned[1].split(',')) {
    const item = piece.trim();
    const match = item.match(/^([A-Za-z]\w*)(?:\s*:\s*([\s\S]+))?$/);
    if (match && !skip.has(match[1])) exports.set(match[1], match[2] || match[1]);
  }
  for (const match of source.matchAll(/\bKit\.([A-Z]\w*)\s*=\s*(?:function\b|[A-Z]\w*\s*;?)/g)) {
    if (!exports.has(match[1])) exports.set(match[1], match[1]);
  }
  // Characters and docs use direct Kit.Name assignments, while UI and objects use Object.assign.
  for (const [name, expression] of exports) {
    if (!/^[A-Z]/.test(name)) continue;
    const primary = expression.startsWith('partAlias(') ? 'Part' : expression.match(/^([A-Z]\w*)/)?.[1] || name;
    const alias = primary !== name;
    const patterns = [new RegExp(`\\bfunction\\s+${primary}\\s*\\(`), new RegExp(`\\bKit\\.${primary}\\s*=\\s*function\\s*\\(`), new RegExp(`\\bconst\\s+${primary}\\s*=`)];
    const index = Math.max(...patterns.map(re => source.search(re)));
    const at = index < 0 ? source.indexOf(`Kit.${name}`) : index;
    const lead = source.slice(Math.max(0, at - 20000), at);
    // Keep the nearest component header, stripping decoration but preserving option/update details.
    const commentStart = Math.max(lead.lastIndexOf('/* Kit.'), lead.lastIndexOf('// Kit.'), lead.lastIndexOf('// Abstract icons'));
    let header = commentStart >= 0 ? lead.slice(commentStart) : '';
    if (header.startsWith('/*')) header = header.slice(0, header.indexOf('*/'));
    else header = header.split('\n').filter((line, i, lines) =>
      i === 0 || lines.slice(0, i).every(previous => /^\s*\/\//.test(previous)) && /^\s*\/\//.test(line)).join('\n');
    header = header.split('\n').map(line => line.replace(/^\s*(?:\/\/|\/\*|\*)\s?/, '').trimEnd())
      .filter(line => line && !/^[=-]{6,}$/.test(line)).join('\n').trim();
    const declaration = source.slice(at).match(/(?:function\s+\w+|Kit\.\w+\s*=\s*function|const\s+\w+\s*=\s*)\s*\(([^)]*)\)/)?.[1];
    const headerCall = header.match(new RegExp(`Kit\\.${primary}\\(([^\\n]*?)\\)`))?.[0];
    const call = headerCall?.includes('parent') ? headerCall : `Kit.${primary}(${declaration || 'parent, options'})`;
    const updateStart = header.search(/\bupdate\(/);
    const originStart = header.search(/\bOrigin:/i);
    const update = updateStart >= 0 ? header.slice(updateStart, originStart > updateStart ? originStart : undefined)
      .replace(/\s+/g, ' ').trim() : 'update(params) — see source for details.';
    const origin = header.match(/Origin:\s*([^\n]+)/i)?.[1] || (header.startsWith('Abstract icons') ? 'Centre.' : file === 'characters' || file === 'objects' ? 'See component header; grounded assets use the floor line.' : 'See component header; place with Engine.place.');
    const callAt = header.indexOf(call);
    const options = callAt >= 0 ? header.slice(callAt + call.length, updateStart >= 0 ? updateStart : originStart).replace(/\s+/g, ' ').trim() :
      (header.match(/Options:([\s\S]*?)(?:update\(|Origin:)/i)?.[1] || '').replace(/\s+/g, ' ').trim();
    const publicCall = expression.startsWith('partAlias(') ? `Kit.${name}(parent, options = {})` :
      alias ? `Kit.${name}` + call.slice(`Kit.${primary}`.length) : call;
    output.push(`### Kit.${name}`, '', `- **Call:** \`${publicCall}\``,
      `- **Options:** ${alias ? `Alias of Kit.${primary}${expression.startsWith('partAlias(') ? ` with kind ${expression.match(/'([^']+)'/)?.[1]}` : ''}. ` : ''}${options || 'See the call signature.'}`,
      `- **Update parameters:** ${update}`, `- **Origin:** ${origin}`, '');
  }
}
await writeFile(path.join(root, 'KIT.md'), output.join('\n') + '\n');
console.log(`wrote KIT.md (${output.filter(x => x.startsWith('### Kit.')).length} factories)`);
